#!/bin/bash

clear
pkill -f rviz
pkill -f gazebo
pkill -f robot_state_publisher
pkill -f gzclient
pkill -f rosout
pkill -f roslaunch
pkill -f rosmaster
pkill -f gzserver
pkill -f node_manager_da
pkill -f master_discover
pkill -f master_sync
pkill -f map_merge
pkill -f node_manager
pkill -f scan_to_scan_fi
pkill -f frontier
pkill -f gmappingpose
pkill -f slam_gmapping
pkill -f static_transfor
pkill -f desaicontroller
pkill -f lasertoworld
pkill -f explorer
pkill -f lasertoworld
pkill -f joy_node
pkill -f teleop_node
pkill -f potentialfieldl
pkill -f celldecompositi
pkill -f frontierdiscove
pkill -f configurationsp
pkill -f ekf_localizatio
pkill -f amcl
pkill -f rqt_tf_tree
pkill -f subgoalnav
pkill -f screen
pkill -f node_manager_da
pkill -f rendezvous
pkill -f frontierfromocc
pkill -f relativedirecti
pkill -f occimageconvert
pkill -f PureStrategySyn
pkill -f StatisticsProfi
pkill -f FBMapFusion.py
pkill -f FusionPose.py
pkill -f dynamiccspace
pkill -f lasernoiser
pkill -f fbmapfusion
pkill -f static_transfor
pkill -f mapproc
pkill -f fbmapfusionnew
pkill -f explorerzones
pkill -f globalmetrics
pkill -f fbmapfusionrela
pkill -f relativeposeest
pkill -f nodelet
pkill -f disparity_view
pkill -f stereo_image_pr
pkill -f tsdf_server
pkill -f kworker
pkill -f esdf_server
pkill -f explorerrendezv
pkill -f pointcloud_to_l
pkill -f mrelocalplanner
pkill -f localdynamicmap
pkill -f cspace
pkill -f python3
pkill -f mockcommunicati
pkill -f standalone_conv
pkill -f averagedisplace
pkill -f alysson2024
pkill -f yamauchi1999