# Noetic-Multi-Robot-Sandbox for multi-robot research using ROS Noetic
# Copyright (C) 2023 Alysson Ribeiro da Silva
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

start_pose_robot_0: {x: 0, y: 0, z: 0, theta: 0}
start_pose_robot_1: {x: 0, y: 0, z: 0, theta: 0}
start_pose_robot_2: {x: 0, y: 0, z: 0, theta: 0}
start_pose_robot_3: {x: 0, y: 0, z: 0, theta: 0}
start_pose_robot_4: {x: 0, y: 0, z: 0, theta: 0}
start_pose_robot_5: {x: 0, y: 0, z: 0, theta: 0}
