# Noetic-Multi-Robot-Sandbox for multi-robot research using ROS Noetic
# Copyright (C) 2025 Alysson Ribeiro da Silva
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Width of the plan is used to get the number of agreements
# and iterate over the matrix.
width: 3

# The k matrix represents the rendezvous plan, where each row is an agreement
# and columns represent robots.
K: [0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0]

# The W matrix represents the agreements activation weights.
#
# The entire plan can be represented by the W matrix alone,
# however, this would imply in loosing the number 0 from the representation.
#
# For example, you can have an agreement [1,1,1] and the weights [0,0,0], which
# in abstract math would imply in an instant agreement fulfillment activation.
W: [0.0, 337.4999999999996, 337.4999999999996, 675.0000000000005, 337.5000000000008, 0.0, 337.5000000000001, 337.5, 0.0, 0.0, 449.9999999999992, 1124.9999999999998, 787.4999999999995, 337.4999999999998, 0.0]

# The first rendezvous location is where all sub-teams
# are supposed to meet first.
first_rendezvous: {x: 6.5, y: 5.5, z: 0.0}